version: 2.1

jobs:
  build:
    executor: nodejs_erbium
    steps:
      - checkout
      - restore_cache:
          key: node-modules-v1-{{ checksum "package-lock.lock" }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Tests
          command: npm run test
      - save_cache:
          key: node-modules-v1-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
                     
executors:
  nodejs_erbium:
    docker:
      - image: circleci/node:erbium
